"""reply_send_tracking

Revision ID: 68c2f44ee1bc
Revises: d9170657f037
Create Date: 2026-04-29 12:42:07.166872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '68c2f44ee1bc'
down_revision: Union[str, Sequence[str], None] = 'd9170657f037'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sent_replies', sa.Column('approved_by', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('sent_replies', sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
    op.add_column('sent_replies', sa.Column('provider_message_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('sent_replies', sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sent_replies', sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('sent_replies', sa.Column('attempt_count', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_sent_replies_provider_message_id'), 'sent_replies', ['provider_message_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sent_replies_provider_message_id'), table_name='sent_replies')
    op.drop_column('sent_replies', 'attempt_count')
    op.drop_column('sent_replies', 'error_message')
    op.drop_column('sent_replies', 'sent_at')
    op.drop_column('sent_replies', 'provider_message_id')
    op.drop_column('sent_replies', 'provider')
    op.drop_column('sent_replies', 'approved_by')
    # ### end Alembic commands ###
