"""initial_schema

Revision ID: d9170657f037
Revises: 
Create Date: 2026-04-29 12:26:48.589173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'd9170657f037'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emails',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sender_email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('subject', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('body', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('processing_status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('provider_message_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('thread_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('in_reply_to', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_raw_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_message_id', name='uq_email_provider_message')
    )
    op.create_index(op.f('ix_emails_id'), 'emails', ['id'], unique=False)
    op.create_index(op.f('ix_emails_provider'), 'emails', ['provider'], unique=False)
    op.create_index(op.f('ix_emails_provider_message_id'), 'emails', ['provider_message_id'], unique=False)
    op.create_index(op.f('ix_emails_sender_email'), 'emails', ['sender_email'], unique=False)
    op.create_index(op.f('ix_emails_thread_id'), 'emails', ['thread_id'], unique=False)
    op.create_table('ai_email_analyses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email_id', sa.Uuid(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('priority', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('recommended_action', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('assigned_team', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('requires_human_review', sa.Boolean(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('extracted_entities', sa.JSON(), nullable=False),
    sa.Column('draft_reply', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['email_id'], ['emails.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_email_analyses_email_id'), 'ai_email_analyses', ['email_id'], unique=True)
    op.create_index(op.f('ix_ai_email_analyses_id'), 'ai_email_analyses', ['id'], unique=False)
    op.create_table('sent_replies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email_id', sa.Uuid(), nullable=False),
    sa.Column('analysis_id', sa.Uuid(), nullable=False),
    sa.Column('reply_subject', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('reply_body', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['ai_email_analyses.id'], ),
    sa.ForeignKeyConstraint(['email_id'], ['emails.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sent_replies_analysis_id'), 'sent_replies', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_sent_replies_email_id'), 'sent_replies', ['email_id'], unique=False)
    op.create_index(op.f('ix_sent_replies_id'), 'sent_replies', ['id'], unique=False)
    op.create_table('workflow_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email_id', sa.Uuid(), nullable=False),
    sa.Column('analysis_id', sa.Uuid(), nullable=False),
    sa.Column('workflow_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('assigned_team', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('priority', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['ai_email_analyses.id'], ),
    sa.ForeignKeyConstraint(['email_id'], ['emails.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_items_analysis_id'), 'workflow_items', ['analysis_id'], unique=True)
    op.create_index(op.f('ix_workflow_items_email_id'), 'workflow_items', ['email_id'], unique=True)
    op.create_index(op.f('ix_workflow_items_id'), 'workflow_items', ['id'], unique=False)
    op.create_table('workflow_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workflow_item_id', sa.Uuid(), nullable=False),
    sa.Column('step', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('details', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workflow_item_id'], ['workflow_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_logs_id'), 'workflow_logs', ['id'], unique=False)
    op.create_index(op.f('ix_workflow_logs_workflow_item_id'), 'workflow_logs', ['workflow_item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflow_logs_workflow_item_id'), table_name='workflow_logs')
    op.drop_index(op.f('ix_workflow_logs_id'), table_name='workflow_logs')
    op.drop_table('workflow_logs')
    op.drop_index(op.f('ix_workflow_items_id'), table_name='workflow_items')
    op.drop_index(op.f('ix_workflow_items_email_id'), table_name='workflow_items')
    op.drop_index(op.f('ix_workflow_items_analysis_id'), table_name='workflow_items')
    op.drop_table('workflow_items')
    op.drop_index(op.f('ix_sent_replies_id'), table_name='sent_replies')
    op.drop_index(op.f('ix_sent_replies_email_id'), table_name='sent_replies')
    op.drop_index(op.f('ix_sent_replies_analysis_id'), table_name='sent_replies')
    op.drop_table('sent_replies')
    op.drop_index(op.f('ix_ai_email_analyses_id'), table_name='ai_email_analyses')
    op.drop_index(op.f('ix_ai_email_analyses_email_id'), table_name='ai_email_analyses')
    op.drop_table('ai_email_analyses')
    op.drop_index(op.f('ix_emails_thread_id'), table_name='emails')
    op.drop_index(op.f('ix_emails_sender_email'), table_name='emails')
    op.drop_index(op.f('ix_emails_provider_message_id'), table_name='emails')
    op.drop_index(op.f('ix_emails_provider'), table_name='emails')
    op.drop_index(op.f('ix_emails_id'), table_name='emails')
    op.drop_table('emails')
    # ### end Alembic commands ###
